<?php

namespace Eadmin\chart\echart;


use Eadmin\chart\Color;
use Eadmin\chart\EchartAbstract;

/**
 * 饼图
 * Class PieChart
 * @package Eadmin\chart
 */
class PieChart extends EchartAbstract
{
    public function __construct($height = '350px', $width = '100%')
    {
        parent::__construct($height, $width);
        $this->options = [
            'title'   => [
                'text' => '',
            ],
            'tooltip' => [
                'trigger'   => 'item',
                'formatter'=>'{b}: {c} ({d}%)',
            ],
            'legend' => [
                'left'   => 'center',
                'bottom' => '0',
                'data'   => [],
            ],
            'series' => []
        ];
    }

    /**
     * 设置数据源
     * @param string $name
     * @param array $data
     */
    public function series(string $name, array $data,array $options = [])
    {
        $names        = array_column($data, 'name');
        $this->legend = array_merge($this->legend, $names);
        $length       = count($this->series);
        $start        = $length * 30 + 10;
        $end          = $start + ($length + 1) * 20;
        if($end > 100){
            $end = 100;
        }
        $this->series[] = array_merge([
            'name'              => $name,
            'type'              => 'pie',
            'roseType'          => 'radius',
            'radius'            => [$start, $end],
            'center'            => ['50%', '38%'],
            'animationEasing'   => 'cubicInOut',
            'animationDuration' => 2600,
            'symbolSize'        => 8,

            'data'              => $data,
            'color'=>Color::ECHART
        ],$options);
        return $this;
    }
    public function jsonSerialize()
    {
        if (count($this->series) == 1) {
            unset($this->series[0]['radius']);
        }
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }

}
