<?php

namespace Eadmin;

class Query extends \think\db\Query
{
    protected $dataAuth = true;
    /**
     * 关闭数据权限
     */
    public function offDataAuth(){
        $this->dataAuth = false;
        return $this;
    }
    public function parseOptions(): array
    {
        if(!isset($this->options['key']) && $this->getModel()){
            $reflectionClass = new \ReflectionClass($this->getModel());
            if($reflectionClass->hasProperty('dataAuth')){
                $property = $reflectionClass->getProperty('dataAuth');
                $property->setAccessible(true);
                $dataAuth = $property->getValue($this->getModel());
                if(isset($this->options['where'])){
                    $where = json_encode($this->options['where']);
                    if(strpos($where,$this->getPk()) === false){
                        Admin::auth()->checkDataAuth($dataAuth,$this);
                    }
                }else{
                    Admin::auth()->checkDataAuth($dataAuth,$this);
                }
            }
        }
        $options =  parent::parseOptions(); // TODO: Change the autogenerated stub
        return $options;
    }
}
